
# diffinfinite
is_diffinfinite: True # we are not extracting from svs files
diffinfinite_macro_path: diffinfinite_macropatches/
diffinfinite_out_path: diffinfinite_out/
out_patch_size: 1024
grayscale_patches: False
using_masks: True
generate_color_mapped_masks: True

split:
  enabled: True
  factor: 4
  presplit_out_path: diffinfinite_presplit_out/
  gen_color_mapped_mask: True

# traditional scans
h5_source_path: dest/patches/
slide_ext: '.svs' # unused
hdf_extension: .h5
target_patch_size: 256
wsi_output_path: out/
limit: 100  # limit = -1 disables the limit, default: -1

transforms:
  prewhiten: False
  using_imagenet: False